model: 'ResNet_DeepLabv3'
dataset_name: 'Pascal'
classes: 20
in_channels: 3
train_path: '/mnt/train'
val_path: '/mnt/val'
names: '/dataset/segmentation/names/pascal_voc.txt'
input_size: 320

workers: 4
epochs: 500
batch_size: 8

save_freq: 1
save_dir: './saved'
gpus: -1

# model Define
backbone: 'ResNet'

optimizer: 'sgd'
optimizer_options:
  lr: 1e-2
  momentum: 0.9

loss: 'focal_loss'

trainer_options:
  check_val_every_n_epoch: 5

experimental_options:
  os: 'windows'
  callbacks:
    - 'SWA'
